grpc:
  client:
    notification-service:
      address: static://${NOTIFICATION_SERVICE_HOST}:8002
      negotiation-type: plaintext
    user-service:
      address: static://${USER_SERVICE_HOST}:8001
      negotiation-type: plaintext
  port: 8000
spring:
  application:
    name: parcel-service
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/testdb
    username: postgres
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
